// this file was automatically generated by generate-deeds-typings.py, please consult that file for more information

import * as BluebirdPromise from "bluebird";
import { DeedsSuccessResult, makeDeedsRequest } from "./basic-request";
export function cancelEditLock(): BluebirdPromise<DeedsSuccessResult>;
export function confirmRegistration(code:string): BluebirdPromise<DeedsSuccessResult>;
export function setEditLock(): BluebirdPromise<DeedsSuccessResult>;
export function getParent(): BluebirdPromise<DeedsSuccessResult>;
export function getSource(): BluebirdPromise<DeedsSuccessResult>;
export function getTags(): BluebirdPromise<DeedsSuccessResult>;
export function getHistory(page:number,revisionsPerPage:number): BluebirdPromise<DeedsSuccessResult>;
export function login(username:string,password:string): BluebirdPromise<DeedsSuccessResult>;
export function setParent(parents:Array<string>): BluebirdPromise<DeedsSuccessResult>;
export function setSource(src:string,title:string,comment:string): BluebirdPromise<DeedsSuccessResult>;
export function setTags(tags:Array<string>): BluebirdPromise<DeedsSuccessResult>;
export function getRatingModule(): BluebirdPromise<DeedsSuccessResult>;
export function register(username:string,email:string,password:string): BluebirdPromise<DeedsSuccessResult>;
export function renamePage(newSlug:string): BluebirdPromise<DeedsSuccessResult>;
export function getRenderedRevision(revKey:number): BluebirdPromise<DeedsSuccessResult>;
export function revertToRevision(revKey:number): BluebirdPromise<DeedsSuccessResult>;
export function getRevision(revKey:number): BluebirdPromise<DeedsSuccessResult>;
export function vote(rating:number): BluebirdPromise<DeedsSuccessResult>;
