language: node_js
node_js:
 - 8.10.0
 - latest

matrix:
  allow_failures:
    - node_js: latest
  fast_finish: true

jobs:
  include:
    - node_js:
     - 8.10.0
    env: UNDEFINE_PROMISES=yes
    - node_js:
     - 8.10.0
    - node_js:
     - latest
       env: UNDEFINE_PROMISES=yes
    - node_js:
     - latest

cache:
 - npm

before_script:
 - make

script:
 - npm run test

notifications:
  email:
    on_success: change
    on_failure: always
