language: node_js
node_js: 10.17.0
python: "3.7"
  
jobs:
  include:
    - env: MINIFY=false
    - env: MINIFY=true INCLUDE_CORE_JS=false PROMISE_TYPE=default

cache:
 - npm

before_script:
 - npm run gulp

script:
 - npm run test

notifications:
  email:
    on_success: change
    on_failure: always
