language: node_js
node_js:
 - 8.10.0
 - latest

matrix:
  allow_failures:
    - node_js: latest
  fast_finish: true

jobs:
  include:
    node_js:
     - 8.10.0
     - latest
    env:
     - UNDEFINE_PROMISES=yes
     - UNDEFINE_PROMISES=no

cache:
 - npm

before_script:
 - make

script:
 - npm run test

notifications:
  email:
    on_success: change
    on_failure: always
