language: node_js
node_js: 10.17.0
  
jobs:
  include:
    - env: UNDEFINE_PROMISES=no
    - env: UNDEFINE_PROMISES=yes

cache:
 - npm

before_script:
 - make

script:
 - npm run test

notifications:
  email:
    on_success: change
    on_failure: always
