language: node_js
node_js: 10.17.0
  
jobs:
  include:
    - env: UGLIFY=false
    - env: UGLIFY=true

cache:
 - npm

before_script:
 - make
 - if [ "$UGLIFY" = "true" ]; then npm run uglify; fi

script:
 - npm run test

notifications:
  email:
    on_success: change
    on_failure: always
