language: node_js

matrix:
  allow_failures:
    - node_js: latest
  fast_finish: true
  
jobs:
  include:
    - name: "8.10.0 Build (Stable)"
      node_js: 8.10.0
    - name: "8.10.0 Build (Forced Polyfill)"
      node_js: 8.10.0
      env: UNDEFINE_PROMISES=yes
    - name: "8.10.0 Build (Transpile to ES2018)"
      node_js: 8.10.0
      env: TS_TRANSPILE_TARGET=es2018

cache:
 - npm

before_script:
 - make

script:
 - npm run test

notifications:
  email:
    on_success: change
    on_failure: always
