language: node_js

matrix:
  allow_failures:
    - node_js: latest
  fast_finish: true
  
jobs:
  include:
    - name: "10.17.0 Build (Stable)"
      node_js: 10.17.0
    - name: "10.17.0 Build (Forced Polyfill)"
      node_js: 10.17.0
      env: UNDEFINE_PROMISES=yes

cache:
 - npm

before_script:
 - make

script:
 - npm run test

notifications:
  email:
    on_success: change
    on_failure: always
