language: node_js
node_js:
 - 8.10.0
 - latest

matrix:
  allow_failures:
    - node_js: latest
  fast_finish: true

jobs:
  include:
    - env: UNDEFINE_PROMISES=yes
      node_js:
        - 8.10.0
        - latest
    - env: UNDEFINE_PROMISES=no
      node_js:
        - 8.10.0
        - latest

cache:
 - npm

before_script:
 - make

script:
 - npm run test

notifications:
  email:
    on_success: change
    on_failure: always
