language: node_js
node_js: 10.17.0
python: "3.7" 

cache:
 - npm

before_script:
 - npm run webpack
 - npm run build-server

script:
 - npm run lint
 - echo "Tests are currently disabled"

notifications:
  email:
    on_success: change
    on_failure: always
